// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lt_gibbs_cpp
List lt_gibbs_cpp(std::vector<std::vector<int>> links_list, std::vector<int> wave, std::vector<int> name, arma::mat y_samp, std::vector<int> strata, int n_strata, int n_waves, int total, int chain_samples, int chain_burnin, int prior_n, std::vector<double> prior_l, int prior_b, int n_0, std::vector<double> l_0, arma::mat b_0, int n_samples, int ncores);
RcppExport SEXP _hiddenmeta_lt_gibbs_cpp(SEXP links_listSEXP, SEXP waveSEXP, SEXP nameSEXP, SEXP y_sampSEXP, SEXP strataSEXP, SEXP n_strataSEXP, SEXP n_wavesSEXP, SEXP totalSEXP, SEXP chain_samplesSEXP, SEXP chain_burninSEXP, SEXP prior_nSEXP, SEXP prior_lSEXP, SEXP prior_bSEXP, SEXP n_0SEXP, SEXP l_0SEXP, SEXP b_0SEXP, SEXP n_samplesSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::vector<int>> >::type links_list(links_listSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type wave(waveSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type name(nameSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y_samp(y_sampSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< int >::type n_strata(n_strataSEXP);
    Rcpp::traits::input_parameter< int >::type n_waves(n_wavesSEXP);
    Rcpp::traits::input_parameter< int >::type total(totalSEXP);
    Rcpp::traits::input_parameter< int >::type chain_samples(chain_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type chain_burnin(chain_burninSEXP);
    Rcpp::traits::input_parameter< int >::type prior_n(prior_nSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type prior_l(prior_lSEXP);
    Rcpp::traits::input_parameter< int >::type prior_b(prior_bSEXP);
    Rcpp::traits::input_parameter< int >::type n_0(n_0SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type l_0(l_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b_0(b_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(lt_gibbs_cpp(links_list, wave, name, y_samp, strata, n_strata, n_waves, total, chain_samples, chain_burnin, prior_n, prior_l, prior_b, n_0, l_0, b_0, n_samples, ncores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hiddenmeta_lt_gibbs_cpp", (DL_FUNC) &_hiddenmeta_lt_gibbs_cpp, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_hiddenmeta(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
