#' Draw population(s) with given network structure for multiple studies
#'
#' Handler for drawing populations with given characteristics for multiple studies. The population characteristics can vary across studies
#'
#' @param pops_args named list of named lists of arguments to \code{get_study_population()}
#'
#' @return Meta tibble data frame with columns
#' \itemize{
#'  \item{"study"}{Character study identifier}
#'  \item{"population"}{List of tibble data frames with whole population information}
#' }
#'
#' @export
#'
#' @import dplyr
#' @importFrom purrr map
#' @importFrom magrittr `%>%`
#' @importFrom methods formalArgs
get_multi_populations <- function(pops_args) {

  return(
    dplyr::tibble(
      study = names(pops_args),
      population =
        purrr::map(names(pops_args), ~ apply_args(study = .x, args = pops_args[[.x]])))
  )

}



#' Draw samples from multiple study populations according to proposed strategies
#'
#' Handler for drawing sample(s) with given characteristics from multiple study populations. The sampling characteristics can vary across and within studies
#'
#' @param data pass-through populations data frame
#' @param samples_args named list of named lists of arguments to sampling function
#'
#' @return Meta tibble data frame with columns
#' \itemize{
#'  \item{"study"}{Character. Study identifier}
#'  \item{"sample"}{Character. Sampling strategy identifier (possible multiple per study}
#'  \item{"population"}{List of tibble data frames. For each combination of study and sampling strategy the data frame includes full population information and respective sampling strategy information}
#' }
#'
#' @export
#'
#' @import dplyr
#' @importFrom purrr map2
#' @importFrom magrittr `%>%`
#' @importFrom methods formalArgs
get_multi_samples <- function(data, samples_args) {

  # if (is.null(data$study)) stop("Data does not contain study variable, probably because it was not generated by get_multi_populations()")

  return(
    lapply(
      X = names(samples_args),
      function(x) { tibble(study = x, sample = names(samples_args[[x]])) }) %>%
      dplyr::bind_rows() %>%
      dplyr::mutate(
        population =
          purrr::map2(.x = study, .y = sample,
                      ~ apply_args(study = .x,
                                   data = data$population[[which(data$study == .x)]],
                                   args = samples_args[[.x]][[.y]]))
      )
  )

}


#' Calculate estimands from multiple study populations
#'
#' Handler for calculating estimand(s) from multiple study populations
#'
#' @param data pass-through populations data frame
#' @param inquiries_args named list of named lists of arguments to estimands functions for each study
#'
#' @return Data frame with estimands and estimand labels
#'
#' @export
#'
#' @import dplyr
#' @importFrom tidyr unnest
#' @importFrom purrr map2
#' @importFrom magrittr `%>%`
#' @importFrom methods formalArgs
get_multi_estimands <- function(data, inquiries_args) {

  # if (is.null(data$study) | is.null(data$sample)) stop("Data does not contain study or population variables, probably because it was not generated by get_multi_samples()")

  return(
    data %>%
      dplyr::mutate(
        estimands =
          purrr::map2(study, population,
                      ~ apply_args(study = .x,
                                   args = inquiries_args[[.x]],
                                   data = .y))
      ) %>%
      tidyr::unnest(estimands) %>%
      # dplyr::mutate(inquiry_label = paste0(study, "_", sample, "_", inquiry_label)) %>%
      dplyr::mutate(inquiry_label = paste0(study, "_", inquiry_label)) %>%
      dplyr::select(inquiry_label, estimand) %>%
      dplyr::distinct(.keep_all = TRUE) %>%
      as.data.frame(x = ., stringsAsFactors = FALSE)
  )

}

#' Calculate estimators from multiple study samples
#'
#' Handler for calculating estimator(s) from multiple study samples
#'
#' @param data pass-through populations data frame
#' @param estimators_args named list of named lists of arguments to estimation functions for each study and sampling strategy
#'
#' @return Data frame with estimands and estimand labels
#'
#' @export
#'
#' @import dplyr
#' @importFrom tidyr unnest
#' @importFrom purrr map2 pmap
#' @importFrom magrittr `%>%`
#' @importFrom methods formalArgs
get_multi_estimates <- function(data, estimators_args) {

  # if (is.null(data$study) | is.null(data$sample)) stop("Data does not contain study or population variables, probably because it was not generated by get_multi_samples()")

  return(
    data %>%
      dplyr::mutate(
        estimator = purrr::map2(study, sample, ~ names(estimators_args[[.x]][[.y]]))
      ) %>%
      tidyr::unnest(estimator) %>%
      dplyr::mutate(
        estimates =
          purrr::pmap(
            list(x = study, y = sample, z = estimator),
            function(x, y, z) {
              apply_args(study = x,
                         data = data$population[[which(data$study == x & data$sample == y)]],
                         args = estimators_args[[x]][[y]][[z]]) }
          )
      ) %>%
      tidyr::unnest(estimates) %>%
      # dplyr::mutate(inquiry_label = paste0(study, "_", sample, "_", inquiry_label)) %>%
      dplyr::mutate(inquiry_label = paste0(study, "_", inquiry_label)) %>%
      dplyr::select(estimator_label, estimate, se, inquiry_label) %>%
      as.data.frame(x = ., stringsAsFactors = FALSE)
  )

}


#'
apply_args <- function(study, args, data = NULL) {

  .handler_pos <- which(names(args) == "handler")
  .handler_arg_pos <- which(names(args) != "handler")

  if (is.null(data) & length(.handler_arg_pos) == 0) {

    stop("Either data or handler arguments have to be provided.")

  } else if (is.null(data) & length(.handler_arg_pos) != 0) {

    return(do.call(what = args[[.handler_pos]],
                   args = args[-c(.handler_pos)]))

  } else if ("tbl" %in% class(data) & length(.handler_arg_pos) == 0) {

    return(do.call(what = args[[.handler_pos]],
                   args = c(data = list(data))))

  } else if ("tbl" %in% class(data) & length(.handler_arg_pos) != 0) {

    return(do.call(what = args[[.handler_pos]],
                   args = c(data = list(data), args[-c(.handler_pos)])))

  }

}
