#' Simulate populations with given network structure for multiple studies with (possibly) varying designs
#'
#' @param pops_args named list of named lists of arguments to \code{get_study_population()} (the set of arguments can be excessive)
#'
#' @return Population data frame for multiple studies
#' @export
#'
#' @import dplyr
#' @importFrom magrittr `%>%`
#' @importFrom methods formalArgs
get_study_populations <- function(pops_args) {

  return(
    tibble(study = names(pops_args),
           population = purrr::map(names(pops_args),
                                   ~ apply_args(study = .x,
                                                 args = pops_args[[.x]])))
  )

}



#' Draw samples from multiple study populations according to proposed strategy
#'
#' Sampling handler for drawing samples with given characteristics from multiple study populations. The sampling characteristics can vary across studies
#'
#' @param data pass-through populations data frame
#' @param samples_args named list of named lists of arguments to sampling function (the set of arguments can be excessive)
#'
#' @return Population or sample data frame for multiple studies
#' @export
#'
#' @import dplyr
#' @importFrom purrr list_along
#' @importFrom magrittr `%>%`
#' @importFrom methods formalArgs
get_study_samples <- function(data, samples_args) {

  if (is.null(data$study)) stop("Data does not contain study variable, probably because it was not generated by get_populations()")

  sampled <-
    lapply(
      X = names(samples_args),
      function(x) { tibble(study = x, sample = names(samples_args[[x]])) }) %>%
    dplyr::bind_rows() %>%
    dplyr::mutate(
      population = purrr::map2(.x = study, .y = sample,
                               ~ apply_args(study = .x,
                                             data = data$population[[which(data$study == .x)]],
                                             args = samples_args[[.x]][[.y]]))
    )

  return(sampled)

}


#'
apply_args <- function(study, args, data = NULL) {

  handler_pos <- which(names(args) == "handler")

  if (is.null(data)) {
    do.call(what = args[[handler_pos]],
            args = args[-c(handler_pos)])
  } else if ("tbl" %in% class(data)) {
    do.call(what = args[[handler_pos]],
            args = c(data = list(data), args[-c(handler_pos)]))
  }

}
