#' Get estimands for several studies
#'
#' @param data pass-through data frame of several study populations
#'
#' @return
#' @export
#'
#' @import dplyr
#' @importFrom magrittr `%>%`
get_meta_estimands <- function(data) {

  if (is.null(data$study)) stop("Data does not contain study variable, probably because it was not generated by get_populations()")

  data %>%
    split(., data$study) %>%
    lapply(
      X = .,
      FUN = function(pop) {

        pop %>%
          get_study_estimands(.) %>%
          dplyr::mutate(estimand_label = paste0(unique(pop$study), "_", estimand_label))

      }) %>%
    dplyr::bind_rows(.)

}
