# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' cpp helper to move vector elements to new indices
#'
#' param x integer vector of elements to be shuffled
#' param old_index integer original index of element to be moved
#' param new_index integer index element should be moved to
#' return shuffled vector
NULL

#' n choose k helper for combn_cpp
#'
#' param n integer number of elements to choose from
#' param k integer number of elements to choose
#' return integer number of ways to choose k items out of n
NULL

#' helper to generate combinations of x k at a time (cpp implementation of combn)
#'
#' param x integer vector of elements to combine
#' param K integer order of combinations
#' return a matrix of k-wise combinations of elements in x
NULL

#' helper to generate single draw from dirichlet distribution
#'
#' param alpha double vector of alpha parameters
#' return a double vector containing a single draw from a dirichlet distribution
NULL

#' cpp implementation of R table
#'
#' param x an integer vector of elements to be counted
#' return an integer vector of counts of unique elements in x (sorted in ascending order of elements in x)
NULL

#' cpp implementation of standard R rep
#'
#' param x integer vector to be repeated
#' param n integer number of repetitions
#' return integer vector x repeated n times
NULL

#' cpp implementation of R rep with each argument
#'
#' param x integer vector of elements to be repeated
#' param n integer number of repetitions
#' return integer vector with each element in x repeated n times in order
NULL

#' helper to generate range of consecutive integers
#'
#' param from integer first integer
#' param to last integer
#' return integer vector of consecutive integers between from and to inclusive
NULL

#' helper to permute sampling data
#'
#' param link_list List holding indices of linked units for each unit
#' param wave integer vector holding the sampling wave of each unit
#' param name integer vector holding the name of each unit
#' return vector of integer vectors holding permuted sampling waves
NULL

#' simple progress bar function
NULL

#' Link-tracing Gibbs sampler
#' @param links_list list of between unit edges
#' @param wave integer vector of rds wave units were sampled in
#' @param name integer vector of unit ids
#' @param y_samp matrix pass through of adjecency matrix generated in get_study_est_linktrace
#' @param strata integer stratum id of each unit
#' @param n_strata integer number of unique strata
#' @param n_waves integer number of sampling waves
#' @param total integer total size of the population
#' @param chain_samples integer number of samples per MCMC chain
#' @param chain_burning integer number of burnin samples per MCMC chain
#' @param prior_n integer power law prior for population size
#' @param prior_l double vector of dirichilet priors for stratum membership
#' @param prior_b integer beta distribution prior for unit links
#' @param n_0 integer initial value for n
#' @param l_0 double vector initial values for l
#' @param b_0 double matrix initial values for b
#' @param n_samples number of samples to draw
#' @param progress bool indicating whether to display progress bar
#' @return a vector of vectors with n_samples population size samples
#' @keywords internal
lt_gibbs_cpp <- function(links_list, wave, name, y_samp, strata, n_strata, n_waves, total, chain_samples, chain_burnin, prior_n, prior_l, prior_b, n_0, l_0, b_0, n_samples, progress) {
    .Call('_hiddenmeta_lt_gibbs_cpp', PACKAGE = 'hiddenmeta', links_list, wave, name, y_samp, strata, n_strata, n_waves, total, chain_samples, chain_burnin, prior_n, prior_l, prior_b, n_0, l_0, b_0, n_samples, progress)
}

