#' Draw samples from multiple study populations according to proposed strategy
#'
#' Sampling handler for drawing samples with given characteristics from multiple study populations. The sampling characteristics can vary across studies
#'
#' @param data pass-through populations data frame
#' @param sampling_variable character string that is used as prefix for all variables generated by RDS sampling (sample identifier, recruiter ID, wave, time of show-up) in each population
#' @param drop_nonsampled logical indicating whether to drop units that are not sampled. Default is \code{FALSE}
#' @param sampling_args named list of named lists of arguments to \code{sample_rds()} (the set of arguments can be excessive)
#' @param sampling_strategy character string giving name of the sampling strategy handler
#'
#' @return
#' @export
#'
#' @import dplyr
#' @importFrom magrittr `%>%`
#' @importFrom pbapply pblapply pboptions
get_hpop_sample <- function(data,
                            sampling_variable = "rds",
                            drop_nonsampled = FALSE,
                            sampling_args,
                            sampling_strategy = c("sample_rds", "sample_prop")
) {

  if (is.null(data$study)) stop("Data does not contain study variable, probably because it was not generated by get_populations()")

  pbapply::pboptions(type = "none")

  sampling_strategy <- match.arg(sampling_strategy)
  switch(sampling_strategy,
         sample_rds = sample_rds,
         sample_prop = sample_prop)

  data %>%
    split(., data$study) %>%
    pbapply::pbmapply(
      pop = .,
      samp = sampling_args,
      FUN = function(pop, samp) {

        do.call(what = sampling_strategy,
                args = c(list(data = pop,
                              sampling_variable = sampling_variable,
                              drop_nonsampled = drop_nonsampled),
                         samp[names(samp) %in% formalArgs(sampling_strategy)]))

      },
      SIMPLIFY = FALSE) %>%
    dplyr::bind_rows(.)

}
