#' Draw probability sample proportional to size (PPS) from single study
#'
#' Sampling handler for drawing proportional sample with given characteristics from individual study population
#'
#' @param data pass-through population data frame
#' @param sample_label character string that is used as prefix for all variables generated by proportional sampling. Default is 'pps'
#' @param drop_nonsampled logical indicating whether to drop units that are not sampled. Default is \code{FALSE}
#' @param target_n_pps target size of proportional sample
#' @param n_clusters number of clusters
#' @param sampling_frame character vector containing all binary vectors identifying sampling frame
#' @param cluster character vector containing name(s) of all cluster variables
#' @param strata character vector containing name(s) of stratifying variables. Currently not implemented
#' @param weights_type character string giving the type of weights to compute. Can be one of "absolute" or "relative". Currently only absolute weights are calculated
#'
#' @return Population or sample data frame for single study with PPS sample characteristics added
#'  \describe{
#'   \item{[sample_label]}{Sampling indicator}
#'   \item{[sample_label]_frame}{Indicator for sampling frame (respondents with 0 cannot be enrolled)}
#'   \item{[sample_label]_strata}{ID of respondent's strata}
#'   \item{[sample_label]_strata_prop}{Proportion of sampling frame in the strata to which respondent belongs}
#'   \item{[sample_label]_cluster}{ID of respondent's cluster}
#'   \item{[sample_label]_cluster_prop}{Proportion of strata in the cluster to which respondent belongs}
#'   \item{[sample_label]_weight}{Sampling weights}
#'  }
#' @export
#'
#' @import data.table
#' @importFrom magrittr `%>%` `%$%`
sample_pps <-
  function(data, sample_label = "pps", drop_nonsampled = FALSE,
           target_n_pps = 400,
           n_clusters = target_n_pps,
           sampling_frame = NULL,
           strata = NULL,
           cluster = NULL,
           weights_type = c("absolute", "relative")
  ) {

    weights_type <- match.arg(weights_type)

    # #check for naming conflicts in strata and cluster
    # conflict <- check_naming_conflict(data,strata,"strata")
    # strata <- conflict$var
    # colnames(data) <- conflict$colnames
    #
    # conflict <- check_naming_conflict(data,cluster,"cluster")
    # cluster <- conflict$var
    # colnames(data) <- conflict$colnames

    .data <- data.table::copy(data)

    .data[,temp_id := .I]
    temp_data <- data.table::copy(.data)
    temp_data <- temp_data[,c("temp_id", sampling_frame, strata, cluster), with=FALSE]
    nmax_per_cluster <- ceiling(target_n_pps/n_clusters)

    if (!is.null(sampling_frame)) {
      temp_data[, frame := Reduce(`&`, .SD), .SDcols=sampling_frame][, frame := as.integer(frame)]
    } else {
      temp_data[, frame := 1]
    }

    # check that sampling is possible
    if (target_n_pps >= sum(temp_data[["frame"]])) {
      stop("Requested PPS sample size is larger than population (or sampling frame) size")
    }


    if(!is.null(strata)) {
      temp_data[, `:=` (strata_id = .GRP, strata_prop = .N), by = strata]
      temp_data[, strata_prop := strata_prop / .N]
    } else {
      temp_data[, `:=` (strata_id = 1, strata_prop = 1)]
    }

    nclustmax_per_strat <- ceiling(n_clusters/length(unique(temp_data[["strata_id"]])))

    temp_data <- split(temp_data, list(temp_data[["strata_id"]]))

    for(i in 1:length(temp_data)) {

      strat_df <- temp_data[[i]]
      # data.table::setDT(strat_df)

      if(!is.null(cluster)) {

        strat_df_2 <-
          strat_df[
            frame == 0,
          ][
            ,`:=` (cluster_id = NA, cluster_prop = NA,
                   sampled_cluster = 0, sampled = 0, weight = NA)
          ]

        strat_df <-
          strat_df[
            frame == 1,
          ][
            , `:=` (cluster_id = .GRP, cluster_prop = .N), by = cluster
          ][
            , cluster_prop := cluster_prop / .N
          ]

        sample <- unique(strat_df, by = c("cluster_id"))
        sample <- sample(sample$cluster_id,
                         size = min(nrow(sample), nclustmax_per_strat),
                         prob = sample$cluster_prop)

        strat_df[
          , `:=` (sampled_cluster = ifelse(cluster_id %in% sample, 1, 0))
        ][
          ,`:=` (sampled = sample(c(rep(1, min(.N, nmax_per_cluster)),
                                    rep(0, max(0, .N - nmax_per_cluster))))),
          by = list(cluster_id, cluster_prop)
        ][
          ,`:=` (sampled = sampled * sampled_cluster)
        ][
          , `:=` (weight = .N / (sum(sampled) * cluster_prop)),
          by = list(cluster_id, cluster_prop)
        ]

        temp_data[[i]] <- data.table::rbindlist(list(strat_df_2,strat_df),
                                                use.names = TRUE)

      } else {

        strat_df_2 <-
          strat_df[
            frame == 0,
          ][
            ,`:=` (cluster_id = NA, cluster_prop = NA,
                   sampled_cluster = 0, sampled = 0, weight = NA)
          ]

        strat_df <-
          strat_df[
            frame == 1,
          ][, `:=` (cluster_id = .I, cluster_prop = 1/.N)
          ][
            , `:=` (sampled = sample(c(rep(1, min(.N, target_n_pps)),
                                       rep(0, max(0, .N - target_n_pps)))))
          ][,`:=` (sampled_cluster = sampled,
                                        weight = sum(frame)/sum(sampled))]

        temp_data[[i]] <- data.table::rbindlist(list(strat_df_2,strat_df),
                                                use.names = TRUE)
      }

    }

    temp_data <- data.table::rbindlist(temp_data)

    cols <- c("frame","cluster_prop","strata_prop","sampled_cluster","weight")
    data.table::setnames(temp_data, old = cols, new = paste(sample_label, cols, sep = "_"))

    temp_data[, paste0(sample_label) := sampled]
    temp_data[, paste0(sample_label, "_cluster") := cluster_id]
    temp_data[, paste0(sample_label, "_strata") := strata_id]

    cols <- paste0(sample_label, "_", cols)
    cols <- c("temp_id", sample_label,
              cols, paste0(sample_label, "_", c("cluster", "strata")))
    temp_data <- temp_data[, ..cols]
    .data <-
      .data[
        temp_data, on = "temp_id"
      ][
        , temp_id := NULL
      ]

    if (drop_nonsampled) .data <- .data[get(sample_label) == 1]

    return(.data)

  }
