#' Draw time-loaction (TLS) sample from single study
#'
#' Sampling handler for drawing TLS sample with given characteristics from individual study population
#'
#' @param data pass-through population data frame
#' @param sampling_variable character string that is used as prefix for all variables generated by TLS sampling. Default is 'tls'
#' @param drop_nonsampled logical indicating whether to drop units that are not sampled. Default is \code{FALSE}
#' @param target_n_tls target number of sampled locations
#'
#' @return Population or sample data frame for single study with TLS sample characteristics added
#' @export
#'
#' @import dplyr
#' @importFrom magrittr `%>%` `%<>%`
sample_tls <-
  function(data, sampling_variable = "tls", drop_nonsampled = FALSE,
           target_n_tls = 2
  ) {

    if (length(grep(pattern = "^loc_", x = names(data))) < target_n_tls)
      stop("Number of requested locations for TLS sample exceeds number of available locations")

    sampled_loc <-
      data %>%
      dplyr::filter(hidden == 1) %>%
      dplyr::summarise(across(starts_with("loc"), mean, .names = "{.col}")) %>%
      t() %>%
      {sample(x = rownames(.), size = target_n_tls, prob = as.vector(.))}

    data %<>%
      dplyr::filter(hidden == 1) %>%
      dplyr::mutate(
        loc_sampled = apply(
          X = .[,c("p_visibility_hidden",
                   names(.)[grepl(pattern = "^loc", names(.))])],
          MARGIN = 1,
          FUN = function(x) {
            if (any(x[-1] == 1)) {
              sample(c(NA, sample(names(x[-1])[which(x[-1] == 1)], size = 1)), size = 1,
                     prob = c((1 - x[1]), x[1]))
            } else {
              NA
            }
          })) %>%
      dplyr::mutate(
        "{ sampling_variable }" :=
          ifelse(!is.na(loc_sampled) & (loc_sampled %in% sampled_loc), 1, 0)) %>%
      dplyr::rename("{ sampling_variable }_loc_sampled" := loc_sampled) %>%
      dplyr::left_join(x = data, y = ., by = "name", suffix = c("", "_dup")) %>%
      dplyr::select(-dplyr::ends_with("_dup"))

    if (drop_nonsampled) data %<>% dplyr::filter_at(dplyr::vars(sampling_variable), ~ . == 1)

    return(data)

  }
