#' Get individual study estimands
#'
#' @param data pass-through population data frame
#'
#' @return
#' @export
#'
#' @import dplyr
#' @importFrom magrittr `%>%`
#' @importFrom purrr map_int
#' @importFrom pbapply pblapply pboptions
hpop_estimands <- function(data) {

  data %>%
    dplyr::mutate(degree = purrr::map_int(links, ~ length(.x)),
                  degree_hidden = purrr::map_int(links, ~ sum(data$hidden[data$name %in% .x]))) %>%
    {
      dplyr::bind_cols(
        dplyr::summarise_at(., dplyr::vars(dplyr::starts_with("known"), hidden, -dplyr::contains("visible")),
                            sum, na.rm  = TRUE),
        dplyr::summarise_at(.,dplyr:: vars(degree, degree_hidden, -dplyr::contains("visible")),
                            mean, na.rm  = TRUE)
      )
    } %>%
    {
      data.frame(estimand_label = c(paste0("size_known_", 1:(ncol(.)-3)),
                                    "size_hidden", "average_degree", "average_degree_hidden"),
                 estimand = unname(t(.)),
                 stringsAsFactors = FALSE)
    }

}

#' Get estimands for several studies
#'
#' @param data pass-through data frame of several study populations
#'
#' @return
#' @export
#'
#' @import dplyr
#' @importFrom magrittr `%>%`
#' @importFrom pbapply pblapply pboptions
get_hpop_estimands <- function(data) {

  if (is.null(data$study)) stop("Data does not contain study variable, probably because it was not generated by get_populations()")

  pbapply::pboptions(type = "none")

  data %>%
    split(., data$study) %>%
    pbapply::pblapply(
      X = .,
      FUN = function(pop) {

        pop %>%
          hpop_estimands(.) %>%
          dplyr::mutate(estimand_label = paste0(unique(pop$study), "_", estimand_label))

      }) %>%
    dplyr::bind_rows(.)

}

