#' Draw proportional sample from single study
#'
#' Sampling handler for drawing proportional sample with given characteristics from individual study population
#'
#' @param data pass-through population data frame
#' @param sampling_variable character string that is used as prefix for all variables generated by proportional sampling. Default is 'prop'
#' @param drop_nonsampled logical indicating whether to drop units that are not sampled. Default is \code{FALSE}
#' @param target_n_prop target size of proportional sample
#'
#' @return
#' @export
#'
#' @import dplyr
#' @import sampling
sample_prop <-
  function(data, sampling_variable = "prop", drop_nonsampled = FALSE, target_n_prop = 400
  ) {

    data <-
      suppressMessages(
        data %>%
          # this is sampling according to proportions of all populations at the moment
          # also this does not include visibility bias
          dplyr::group_by_at(dplyr::vars(dplyr::starts_with("known"), hidden, -ends_with("visible"))) %>%
          dplyr::summarize(prop_share = dplyr::n()/nrow(data)) %>%
          dplyr::left_join(data, .) %>%
          dplyr::mutate(
            prop_prob = sampling::inclusionprobabilities(a = prop_share,
                                                         n = target_n_prop),
            "{ sampling_variable }" := sampling::UPmidzuno(prop_prob)) %>%
          dplyr::select(-links) %>%
          dplyr::rename("{ sampling_variable }_share" := prop_share,
                        "{ sampling_variable }_prob" := prop_prob) %>%
          dplyr::left_join(data, .)
      )


    if (drop_nonsampled) data %<>% dplyr::filter_at(dplyr::vars(sampling_variable), ~ . == 1)

    return(data)

  }
