#' Draw proportional sample (PPS) from single study
#'
#' Sampling handler for drawing proportional sample with given characteristics from individual study population
#'
#' @param data pass-through population data frame
#' @param sampling_variable character string that is used as prefix for all variables generated by proportional sampling. Default is 'pps'
#' @param drop_nonsampled logical indicating whether to drop units that are not sampled. Default is \code{FALSE}
#' @param target_n_pps target size of proportional sample
#' @param group_pattern character string containing regular expression to match all groups used for proportional sampling
#'
#' @return Population or sample data frame for single study with PPS sample characteristics added
#' @export
#'
#' @import dplyr
sample_pps <-
  function(data, sampling_variable = "pps", drop_nonsampled = FALSE,
           target_n_pps = 400, group_pattern = "^known"
  ) {

    if (target_n_pps >= nrow(data)) stop("Requested PPS sample size is larger than population size")

    data <-
      suppressMessages(
        data %>%
          # this is sampling according to proportions of all populations at the moment
          # also this does not include visibility bias
          dplyr::group_by_at(dplyr::vars(dplyr::matches(group_pattern),
                                         -ends_with("visible"))) %>%
          dplyr::summarize(prop_share = dplyr::n()/nrow(data)) %>%
          dplyr::left_join(data, .) %>%
          dplyr::mutate(
            "{ sampling_variable }" :=
              ifelse(name %in% sample(x = name, size = target_n_pps, prob = prop_share), 1, 0)
          ) %>%
          dplyr::rename("{ sampling_variable }_share" := prop_share)
      )


    if (drop_nonsampled) data %<>% dplyr::filter_at(dplyr::vars(sampling_variable), ~ . == 1)

    return(data)

  }
