#' Draw probability sample proportional to size (PPS) from single study
#'
#' Sampling handler for drawing proportional sample with given characteristics from individual study population
#'
#' @param data pass-through population data frame
#' @param sampling_variable character string that is used as prefix for all variables generated by proportional sampling. Default is 'pps'
#' @param drop_nonsampled logical indicating whether to drop units that are not sampled. Default is \code{FALSE}
#' @param target_n_pps target size of proportional sample
#' @param n_clusters number of clusters
#' @param sampling_frame character vector containing all binary vectors identifying sampling frame
#' @param cluster character vector containing name(s) of all cluster variables
#' @param strata character vector containing name(s) of stratifying variables. Currently not implemented
#' @param weighs_type character string giving the type of weights to compute. Can be one of "absolute" or "relative". Currently only absolute weights are calculated
#'
#' @return Population or sample data frame for single study with PPS sample characteristics added
#' @export
#'
#' @import dplyr
#' @importFrom tidyr nest unnest
#' @importFrom magrittr `%<>%`
#' @importFrom purrr when map_int
sample_pps <-
  function(data, sampling_variable = "pps", drop_nonsampled = FALSE,
           target_n_pps = 400,
           n_clusters = target_n_pps,
           sampling_frame = NULL,
           strata = NULL,
           cluster = NULL,
           weighs_type = c("absolute", "relative")
  ) {

    weighs_type <- match.arg(weighs_type)

    data <- dplyr::mutate(data, temp_id = 1:n())
    temp_data <- data %>% dplyr::select(temp_id, all_of(c(sampling_frame, strata, cluster)))
    nmax_per_cluster <- target_n_pps/n_clusters


    if (!is.null(sampling_frame)) {
      temp_data %<>%
        dplyr::mutate(frame = apply(.[,sampling_frame], 1, function(x) as.integer(all(x == 1))))
    } else {
      temp_data %<>% dplyr::mutate(frame = 1)
    }

    # check that sampling is possible
    if (target_n_pps >= sum(temp_data$frame))
      stop("Requested PPS sample size is larger than population (or sampling frame) size")

    # if (!is.null(strata)) {
    #   temp_data <-
    #     temp_data %>%
    #     dplyr::group_by(dplyr::across(dplyr::all_of(strata)))
    # }

    if (!is.null(cluster)) {
      temp_data %<>%
        tidyr::nest(dat = -dplyr::all_of(cluster)) %>%
        dplyr::mutate(cluster_id = 1:n(),
                      cluster_prop = purrr::map_int(dat, ~ nrow(.x)),
                      cluster_prop = cluster_prop/sum(cluster_prop)) %>%
        tidyr::unnest(cols = c(dat))

      temp_data %<>%
        dplyr::filter(frame == 1) %>%
        tidyr::nest(dat = -c(cluster_id, cluster_prop)) %>%
        dplyr::mutate(
          sampled_cluster =
            ifelse(cluster_id %in% sample(x = cluster_id,
                                          size = n_clusters,
                                          prob = cluster_prop), 1, 0),
          dat =
            purrr::map(
              dat,
              ~ dplyr::mutate(.x,
                              sampled = sample(c(rep(1,min(n(), nmax_per_cluster)),
                                                 rep(0,max(0, n() - nmax_per_cluster))))))
        ) %>%
        tidyr::unnest(cols = c(dat)) %>%
        dplyr::bind_rows(dplyr::filter(temp_data, frame != 1),
                         .) %>%
        dplyr::mutate(
          across(c(sampled_cluster, sampled), ~ ifelse(is.na(.), 0, 1)),
          weight = sum(frame)/nmax_per_cluster) %>%
        dplyr::rename_with(.cols = c(frame, cluster_id, cluster_prop, sampled_cluster, weight),
                           ~ paste0(sampling_variable, "_", gsub("^sampled$", "", x = .))) %>%
        dplyr::rename("{ sampling_variable }" := sampled)
    } else {
      temp_data %<>%
        dplyr::mutate(cluster_id = 1:n(),
                      cluster_prop = 1/n(),
                      weight = 1/sum(frame)) %>%
        dplyr::filter(frame == 1) %>%
        dplyr::mutate(sampled =
                        sample(c(rep(1,min(n(), target_n_pps)),
                                 rep(0,max(0, n() - target_n_pps)))),
                      sampled_cluster = sampled) %>%
        dplyr::bind_rows(dplyr::filter(temp_data, frame != 1),
                         .) %>%
        dplyr::mutate(across(c(sampled_cluster, sampled), ~ ifelse(is.na(.), 0, .))) %>%
        dplyr::rename_with(.cols = c(frame, cluster_id, cluster_prop, sampled_cluster, weight),
                           ~ paste0(sampling_variable, "_", gsub("^sampled$", "", x = .))) %>%
        dplyr::rename("{ sampling_variable }" := sampled)
    }

    data <-
      suppressMessages(
        temp_data %>%
          dplyr::select(temp_id, all_of(sampling_variable), starts_with(sampling_variable)) %>%
          dplyr::left_join(data, .) %>%
          dplyr::select(-temp_id)
      )

    if (drop_nonsampled) {
      data %<>% dplyr::filter(dplyr::across(dplyr::all_of(sampling_variable), ~ . == 1))
    }

    return(data)

  }
