#' Draw proportional sample from single study
#'
#' Sampling handler for drawing proportional sample with given characteristics from individual study population
#'
#' @param data pass-through population data frame
#' @param sampling_variable character string that is used as prefix for all variables generated by RDS sampling (sample identifier, recruiter ID, wave, time of show-up)
#' @param drop_nonsampled logical indicating whether to drop units that are not sampled. Default is \code{FALSE}
#' @param target_size_prop target size of proportional sample
#'
#' @return
#' @export
#'
#' @import dplyr
sample_prop <-
  function(data, sampling_variable = "prop", drop_nonsampled = FALSE, target_size_prop = 400
  ) {

    sampled <-
      suppressMessages(
        data %>%
          dplyr::group_by_at(dplyr::vars(dplyr::starts_with("known"))) %>%
          dplyr::summarize(sample_prop = dplyr::n()/nrow(data)) %>%
          dplyr::left_join(data, .) %>%
          dplyr::slice_sample(n = target_size_prop, weight_by = sample_prop) %>%
          dplyr::select(-links)
      )

    data[,sampling_variable] <- as.integer(data$name %in% sampled$name)

    suppressMessages(
      data %<>% dplyr::left_join(., sampled)
    )


    if (drop_nonsampled) data %<>% dplyr::filter_at(dplyr::vars(sampling_variable), ~ . == 1)

    return(data)

  }
